# data
dataset: uci

# info
num_classes: 6
image_size: [128,9]
num_epochs: 150
print_freq: 100

# optimizer
optimizer: adam


# lr
lr: 1e-4


# model profiling
profiling: [gpu]

#
#random_seed: 1995
batch_size: 64

log_dir: logs/
model: models.cnn_uci
depth: 3
#widen_factor: 10
#dropoutrate: 0.0
#reset_parameters: True
width_mult_list: [0.10,0.15,0.20,0.25,0.3,0.35,0.40,0.45,0.5,0.55,0.60,0.65,0.70,0.75,0.80,0.85,0.90,0.95,1.0]
width_mult_range: [0.10, 1.0]
resolution_list: [[128,9],[124,9],[120,9],[116,9],[112,9],[108,9],[104,9] ,[100,9],[96,9]] #从最大尺度开始
# test pretrained resume
test_only: False
pretrained: ''
resume: ''
