# data
dataset: unimib

# info
num_classes: 17
image_size: [151,3]
num_epochs: 150
print_freq: 100

# optimizer
optimizer: adam


# lr
lr: 1e-4


# model profiling
profiling: [gpu]

#
#random_seed: 1995
batch_size: 128

log_dir: logs/
model: models.cnn_unimib
depth: 3
#widen_factor: 10
#dropoutrate: 0.0
#reset_parameters: True
width_mult_list: [0.10,0.15,0.20,0.25,0.3,0.35,0.40,0.45,0.5,0.55,0.60,0.65,0.70,0.75,0.80,0.85,0.90,0.95,1.0]
width_mult_range: [0.10, 1.0]
resolution_list: [[151,3],[144,3],[136,3], [120,3],[112,3]]  #从最大尺度开始
# test pretrained resume
test_only: False
pretrained: ''
resume: ''
